spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tools?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql@76!123
  jpa:
    hibernate:
    # Hibernate ddl auto
    #   create          Create the schemaand destory previous data
    #   validate        Validate the schema, make no changes to the databases
    #   create-drop     DisableDDL handling
    #   update           Update the schema if necessary
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  redis:
    database: 1
    host: 127.0.0.1
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    timeout: 0
    password: redis76!123
server:
  port: 80

prefox:
 official:
   email:
    host: smtp.mxhichina.com
    port: 25
    from: prefox@prefox.site
    user: prefox@prefox.site
    pass: prefox76!123
#    host: smtp.googlemail.com
#    port: 465
#    from: prefoxchina@gmail.com
#    user: prefoxchina@gmail.com
#    pass: google@109964
#    host: smtp-mail.outlook.com
#    port: 587
#    from: pre_fox@outlook.com
#    user: pre_fox@outlook.com
#    pass: outlook@109964
   website: http://prefox.site/@project.name@
 file:
  upload:
   temp: /usr/local/webapps/prefox/file/upload/temp
   basic: /usr/local/webapps/prefox/file/upload/basic
  download:
   temp: /usr/local/webapps/prefox/file/download/temp
 openOffice:
   host: 127.0.0.1
   port: 8100
   home: /opt/openoffice4
 nginx: http://111.230.23.211:9090/

fonts:
   simsun: /usr/local/tools/data/SIMSUN.TTC
